service:
  name: auth

plugins:
  - serverless-webpack

custom:
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs6.10

functions:
  auth:
    handler: auth.authorize
