service:
  name: auth

plugins:
  - serverless-webpack

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs6.10

resources:
  ${file(./aws-cloudformation-template.yml)}

functions:
  auth:
    handler: auth.authorize
