AWSTemplateFormatVersion: "2010-09-09"
Description: The aws resource template for serverless app

Resources:
  todoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Todos
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
